# Creating rarefaction plot generated by mothur
# code to generate rarefaction (step 26) is here: https://github.com/jessicamizzi/mothur-commands/blob/master/workflow.md

install.packages("ggplot2")
install.packages("reshape2")
library("reshape2")
library("ggplot2")

# load data
# replace this with your data file
rareDataMessy <- read.table("~/subset-CS-Y-16S-reads/stability.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.an.unique_list.groups.rarefaction", header = TRUE)


# Clean data file (no high or low confidence intervals)

# grep command may need to be changed. The idea is to pick out columns that are not hci or lci
rareDataColumnsPrimary <- rareDataMessy[grepl("X0", names(rareDataMessy))]

# this takes numsampled column from original data
numSampled <- rareDataMessy[ ,c("numsampled")]

# this combines numsampled column with grepped columns
rareData <- cbind(numSampled,rareDataColumnsPrimary)

## Plot data with ggplot2

# transform data to long form
longRareData <- melt(rareData, id.vars = "numSampled")
head(longRareData)

# plotting
options(scipen = 100000)
ggplot(data = longRareData,
       aes(x = numSampled, y = value, color = variable)) +
  geom_line() + 
  ggtitle("Temporal 16S Community from Corn Stover Samples in Cow Y\n") +
  labs(x = "Number of Samples", y = "Number of OTUs") +
  guides(color = guide_legend("Legend")) +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))



## Optional
# Alternatively, you can use plot to create an uglier plot

plot(x=rareData$numSampled, y=rareData$X0.03.16S.V4.CS.Y.36hr, xlab="Number of Tags Sampled", ylab="OTUs", type="l", col="black", font.lab=10)
points(x=rareData$numSampled, y=rareData$X0.03.16S.V4.CS.Y.8hr, type = "l", col = "blue")
points(x=rareData$numSampled, y=rareData$X0.03.16S.V4.CS.Y.24hr, type = "l", col = "blueviolet")
points(x=rareData$numSampled, y=rareData$X0.03.16S.V4.CS.Y.0hr, type = "l", col = "deeppink")
points(x=rareData$numSampled, y=rareData$X0.03.16S.V4.CS.Y.48hr, type = "l", col = "seagreen")
points(x=rareData$numSampled, y=rareData$X0.03.16S.V4.CS.Y.72hr, type = "l", col = "sienna")
legend(x=300000, y = 2500, c("0  hr    ", "8  hr", "24 hr", "36 hr", "48 hr", "72 hr"), c("deeppink", "blue", "blueviolet", "black", "seagreen", "sienna"))
title(main = "Temporal 16S Community in Cow Y on Corn Stover Diet")


